### PR TITLE
DUAL ROWS STATUSBAR [ 1/2 ]

### PR DESCRIPTION
**Pull request by 703joko**

### CODE REVIEW

**Comment by SuperDroidBond** [comment]
@703joko Who's that guy

**Comment by 703joko** [comment]
Rejected??

**Comment by 703joko** [comment]
I am noob, want to make a contributions

Pada tanggal Rab, 2 Sep 2020 20.58, SuperDroidBond <notifications@github.com>
menulis:

**Comment by xAbdaziz** [comment]
We welcome contributions but you must give proper authorship

**Comment by 703joko** [comment]
Sure, but i dont know how. I am really noob at the github.

Pada tanggal Sel, 8 Sep 2020 16.02, xawlw <notifications@github.com>
menulis:

**Comment by xAbdaziz** [comment]
@703joko There's a lot of guides online, Just search and learn

**Comment by 703joko** [comment]
Ahh okay, sure. Thanks, will try next PR

**Comment by SuperDroidBond** [comment]
Connect to us on Telegram please. You can ping me on TG @SuperDroidBond username. Will guide you through.

**Comment by 703joko** [comment]
Sure. Thanks

Pada tanggal Sel, 8 Sep 2020 17.52, SuperDroidBond <notifications@github.com>
menulis:

**Pull request closed without merging**
