### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by ultranoob-5**

### CODE REVIEW

**Comment by Darkstar085** [comment]
Use script & directly push them to gerrit ...

**Comment by xAbdaziz** [comment]
@Sweeto143 yea we're working on this

**Comment by Darkstar085** [comment]
> @Sweeto143 yea we're working on this

Tag me when done.. me will kang it 😘

**Comment by xAbdaziz** [comment]
> > @Sweeto143 yea we're working on this
> 
> Tag me when done.. me will kang it

here ;P
https://github.com/Project-Xtended/manifest/commit/577d85fb9711a91a66d841e9a6f08765a88d6fef

**Pull request closed without merging**
