### PR TITLE
SystemUI : Dual statusbar

### PR DESCRIPTION
**Pull request by 703joko**
Thanks to @ZeNiXxX for his commit .
https://github.com/Corvus-ROM/android_frameworks_base/commit/3625126addac80656b66212cc60e39d4b8475495

### CODE REVIEW

**Comment by xawlw** [comment]
@703joko Still not correct, that's not how cherry-pick works

**Comment by 703joko** [comment]
Damn. Really i am very very noob. Can u tell me or forget it.

Pada tanggal Sel, 8 Sep 2020 16.33, xawlw <notifications@github.com>
menulis:

**Comment by xawlw** [comment]
@703joko As I said you should Google it, learn how to cherry-pick and give proper authorship

**Comment by 703joko** [comment]
Will try ,, I will study first

Pada tanggal Sel, 8 Sep 2020 16.41, xawlw <notifications@github.com>
menulis:

**Comment by 703joko** [comment]
Wait..
But man. We have a different source, we cannot charry-pick.
I'm working on getting him to work at Xtended.You can compare my commit
differences with commit mr zennix

Pada tanggal Sel, 8 Sep 2020 16.41, xawlw <notifications@github.com>
menulis:

**Comment by xawlw** [comment]
You can make it work, cherry-pick and fix conflicts

**Comment by 703joko** [comment]
Ahh okay sir

Pada tanggal Sel, 8 Sep 2020 16.56, xawlw <notifications@github.com>
menulis:

**Comment by SuperDroidBond** [comment]
@703joko Wtf is going on in main org github

**Comment by 703joko** [comment]
Sorry for the fuss

Pada tanggal Sel, 8 Sep 2020 17.21, SuperDroidBond <notifications@github.com>
menulis:

**Pull request closed without merging**
